maps/agctf_outland.txt
maps/agctf_outland.res
overviews/agctf_outland.txt
overviews/agctf_outland.tga
gfx/env/mercury_up.tga
gfx/env/mercury_dn.tga
gfx/env/mercury_lf.tga
gfx/env/mercury_rt.tga
gfx/env/mercury_ft.tga
gfx/env/mercury_bk.tga